# Form implementation generated from reading ui file 'ui/bookings_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Admin_Wind(object):
    def setupUi(self, Admin_Wind):
        Admin_Wind.setObjectName("Admin_Wind")
        Admin_Wind.resize(1012, 771)
        self.centralwidget = QtWidgets.QWidget(parent=Admin_Wind)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_edit.setGeometry(QtCore.QRect(620, 670, 141, 41))
        self.btn_edit.setObjectName("btn_edit")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 200, 851, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bookings_table = QtWidgets.QTableView(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bookings_table.sizePolicy().hasHeightForWidth())
        self.bookings_table.setSizePolicy(sizePolicy)
        self.bookings_table.setMaximumSize(QtCore.QSize(900, 450))
        self.bookings_table.setObjectName("bookings_table")
        self.bookings_table.horizontalHeader().setStretchLastSection(True)
        self.bookings_table.verticalHeader().setHighlightSections(False)
        self.bookings_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.bookings_table, 0, 0, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(780, 670, 141, 41))
        self.btn_delete.setObjectName("btn_delete")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 160, 16, 21))
        self.label.setObjectName("label")
        self.date_from = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_from.setGeometry(QtCore.QRect(100, 160, 110, 22))
        self.date_from.setObjectName("date_from")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 160, 31, 21))
        self.label_2.setObjectName("label_2")
        self.date_to = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_to.setGeometry(QtCore.QRect(300, 160, 110, 22))
        self.date_to.setObjectName("date_to")
        self.btn_filter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_filter.setGeometry(QtCore.QRect(470, 160, 93, 28))
        self.btn_filter.setObjectName("btn_filter")
        self.btn_show_all = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_show_all.setGeometry(QtCore.QRect(600, 160, 93, 28))
        self.btn_show_all.setObjectName("btn_show_all")
        Admin_Wind.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Admin_Wind)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 26))
        self.menubar.setObjectName("menubar")
        Admin_Wind.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Admin_Wind)
        self.statusbar.setObjectName("statusbar")
        Admin_Wind.setStatusBar(self.statusbar)

        self.retranslateUi(Admin_Wind)
        QtCore.QMetaObject.connectSlotsByName(Admin_Wind)

    def retranslateUi(self, Admin_Wind):
        _translate = QtCore.QCoreApplication.translate
        Admin_Wind.setWindowTitle(_translate("Admin_Wind", "MainWindow"))
        self.btn_edit.setText(_translate("Admin_Wind", "Редактировать"))
        self.btn_delete.setText(_translate("Admin_Wind", "Удалить"))
        self.label.setText(_translate("Admin_Wind", "С:"))
        self.label_2.setText(_translate("Admin_Wind", "По:"))
        self.btn_filter.setText(_translate("Admin_Wind", "Фильтровать"))
        self.btn_show_all.setText(_translate("Admin_Wind", "Показать все"))
