# Form implementation generated from reading ui file 'ui/register_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(465, 768)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 140, 281, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_name = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.input_name.setEnabled(True)
        self.input_name.setObjectName("input_name")
        self.verticalLayout.addWidget(self.input_name)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.input_surname = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.input_surname.setObjectName("input_surname")
        self.verticalLayout.addWidget(self.input_surname)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.input_lastname = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.input_lastname.setObjectName("input_lastname")
        self.verticalLayout.addWidget(self.input_lastname)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_phone = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.input_phone.setObjectName("input_phone")
        self.verticalLayout.addWidget(self.input_phone)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_login = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.input_login.setObjectName("input_login")
        self.verticalLayout.addWidget(self.input_login)
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.input_password = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.input_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.input_password.setObjectName("input_password")
        self.verticalLayout.addWidget(self.input_password)
        self.btn_register = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_register.sizePolicy().hasHeightForWidth())
        self.btn_register.setSizePolicy(sizePolicy)
        self.btn_register.setMouseTracking(False)
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout.addWidget(self.btn_register)
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(160, 60, 161, 31))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Имя"))
        self.label_3.setText(_translate("Form", "Фамилия"))
        self.label_5.setText(_translate("Form", "Отчество"))
        self.label_2.setText(_translate("Form", "Телефон"))
        self.label_4.setText(_translate("Form", "Логин"))
        self.label_6.setText(_translate("Form", "Пароль"))
        self.btn_register.setText(_translate("Form", "Зарегистрироваться"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Регистрация</span></p></body></html>"))
